services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: usd-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  redis:
    image: redis:7-alpine
    container_name: usd-redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: usd-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  postgres:
    image: pgvector/pgvector:pg16
    container_name: usd-postgres
    environment:
      POSTGRES_USER: usd
      POSTGRES_PASSWORD: usd
      POSTGRES_DB: usd_kb
    ports:
      - "5432:5432"
